version: '3'

services:
  nginx:
    build: ./Src/Server/Nginx
    restart: always
    ports:
     - 80:80
    deploy:
      replicas: 3

  vindskydd_api:
    image: vindskydd_api:latest
    restart: always
